apiVersion: apps/v1
kind: Deployment
metadata:
  name: student04-deployment
  namespace: student04
spec:
  selector:
    matchLabels:
      app: student04
  template:
    metadata:
      labels:
        app: student04
    spec:
      containers:
      - name: student04
        image: registry.tanzu.dk/ops2devops/student04:v1
