apiVersion: apps/v1
kind: Deployment
metadata:
  name: student04-deployment
  namespace: student04
spec:
  selector:
    matchLabels:
      app: student04
  template:
    metadata:
      labels:
        app: student04
    spec:
      containers:
      - name: student04
        image: registry.tanzu.dk/ops2devops/student04:master
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: student04
spec:
  type: NodePort
  selector:
    app: student04
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30014 # Remember to change to student number.

